### ISSUE TITLE
Send text with emoji to server.

### ISSUE THREAD

**Issue by vgevorgyan** [rockerhieu/emojicon#1]
Hello,

I have problem with send the text with emoji to server.
When I send they are becoming to ???.
Server side work perfectly, because I have tested it with the iOS version.

Any suggestion?

Thanks,
Vardan

**Comment by MustanserIqbal93** [comment]
I got the solution for saving Emoji in Database 
do it like this in android code

> Encoding:

`byte[] data = editTextFieldWithEmojis.getText().toString().getBytes("UTF-8");
                base64String = Base64.encodeToString(data, Base64.DEFAULT);`

> Decofing

`byte[] data = Base64.decode(stringWithEmojis, Base64.DEFAULT);
                newStringWithEmojis = new String(data, "UTF-8");`
