### ISSUE TITLE
Push the latest changes to Maven Repository

### ISSUE THREAD

**Issue by pfives** [rockerhieu/emojicon#101]
Hey @rockerhieu can we get an update (1.3.3?) with the new iOS 9.1 emojis pushed to the Maven Repo? Thanks!

**Comment by rockerhieu** [comment]
I'm on vacation, I will do it in 2-3 days :dancer:

**Comment by laylizzlle** [comment]
we are still waiting

**Comment by rockerhieu** [comment]
Pushed to maven, please wait up to 2 hours.
