### ISSUE TITLE
Android studio failed to find your jar 

### ISSUE THREAD

**Issue by uday231992** [rockerhieu/emojicon#115]
Android studio failed to find the jar file of dependencies.

Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find com.github.rockerhieu:emojicon:v1.0.
     Searched in the following locations:
         https://jcenter.bintray.com/com/github/rockerhieu/emojicon/v1.0/emojicon-v1.0.pom
         https://jcenter.bintray.com/com/github/rockerhieu/emojicon/v1.0/emojicon-v1.0.jar

**Comment by rockerhieu** [comment]
The latest version is `1.3.3`.
