### ISSUE TITLE
How to prevent emojicons from showing at the bottom

### ISSUE THREAD

**Issue by WanClem** [rockerhieu/emojicon#119]
Hello,nice library Emojicon...I tried showing Emojicon in EmojiconTextView but the Emoticon is showing at the bottom of the EmojiconTextView instead of flowing along with the other characters in the EmojiconTextView..What do I do? Thanks.

**Comment by burntbear00** [comment]
I also have this problem.
Btw, i used a alternative method to solve it.
Add these three line in EmojiconTextView on your XML file.
android:lineSpacingMultiplier="1.15"
            android:textSize="17sp"
            emojicon:emojiconSize="24sp"

**Comment by WanClem** [comment]
Thanks @burntbear00 ,it worked,U rock!!!

**Comment by burntbear00** [comment]
Nice :) +1:
