### ISSUE TITLE
failed to resolve 

### ISSUE THREAD

**Issue by tjoshi03** [rockerhieu/emojicon#133]
Error:(35, 13) Failed to resolve: com.github.rockerhieu:emojicon:v1.0
<a href="openFile:C:/Users/lenovo/AndroidStudioProjects/NewInCity/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by rockerhieu** [comment]
Should be `io.github.rockerhieu:emojicon:1.4.0` now.
