### ISSUE TITLE
Emojis too small

### ISSUE THREAD

**Issue by edu1525** [rockerhieu/emojicon#149]
Hi, I'm using emojicon inside a FrameLayout, but the emoticons are really small, how can I change those size? Thanks!

**Comment by saeed-rz** [comment]
did u change the width and height of emoji cell?

**Comment by edu1525** [comment]
No, i didn't. How can I do it? Thanks.
________________________________
De: Saeed_rz <notifications@github.com>
Enviado: domingo, 6 de novembro de 2016 04:14:43
Para: rockerhieu/emojicon
Cc: edu1525; Author
Assunto: Re: [rockerhieu/emojicon] Emojis too small (#149)


did u change the width and height of emoji cell?

-

**Comment by saeed-rz** [comment]
in emojicon_grid.xml file change grid property like below
`<GridView xmlns:android="http://schemas.android.com/apk/res/android"
          android:id="@+id/Emoji_GridView"
          android:layout_width="fill_parent"
          android:layout_height="fill_parent"
          android:background="@android:color/transparent"
          android:cacheColorHint="@android:color/transparent"
          android:columnWidth="44dip"
          android:horizontalSpacing="0dip"
          android:numColumns="auto_fit"
          android:scrollbars="vertical"
          android:verticalSpacing="0dip" />`

and in emojicon_item change emojiconTextView to 
`<com.cooper.infinitechat.emoji.EmojiconTextView
        android:layout_gravity="center"
        android:id="@+id/emojicon_icon"
        android:layout_width="40dip"
        android:layout_height="40dip"
        emojicon:emojiconSize="36dip"
        android:gravity="center" />`

**Comment by rockerhieu** [comment]
Using `emojicon:emojiconSize="36dip"` like @saeed-rz mentioned should work.
