### ISSUE TITLE
Just one column emoji in io.github.rockerhieu.emojicon.EmojiconsView

### ISSUE THREAD

**Issue by wanyt** [rockerhieu/emojicon#151]
I copy the code in com.rockerhieu.emojicon.example.EmojiconsActivity and R.layout.activity_emojicons into my project, when I run my project it just one column emoji in EmojiconsView. This is the picture link: http://oc3k2hfgm.bkt.clouddn.com/282515153315829018.jpg, Can you help me to solve the problem.

**Comment by rockerhieu** [comment]
You can specify the number of column just like you can with a normal GridView. See https://github.com/rockerhieu/emojicon/blob/master/library/src/main/res/values/styles.xml.

**Comment by omercakici** [comment]
two different namespace !!!! 
the codebase namespace is: io.github.rockerhieu 
but gradle jar file com.rockerhieu.emojicon 

and all side conflicts!!

**Comment by omercakici** [comment]
there is EmojiconPage struct in     

compile group: 'io.github.rockerhieu', name: 'emojicon', version: '1.3.4'
