### ISSUE TITLE
In my android.support.v4.app.Fragment I can not make the method setEmojiconFragment work

### ISSUE THREAD

**Issue by sallezze** [rockerhieu/emojicon#152]
Hello everyone.

In my android.support.v4.app.Fragment I can not make the method work

 Private void setEmojiconFragment (boolean useSystemDefault) {
       GetSupportFragmentManager ()
                .beginTransaction ()
                .replace (R.id.emojicons, EmojiconsFragment.newInstance (useSystemDefault))
                .commit ();
    }

I have tried in several ways to get the getSupportFragmentManager () function, but it always returns me the java.lang.IllegalArgumentException error: xx.xxx.xxxxxx.app.activities.MainActivity@7fa5758 must implement interface OnEmojiconBackspaceClickedListener

Could someone give me a light?

Thank you

**Comment by rockerhieu** [comment]
The host activity must implement interface `OnEmojiconBackspaceClickedListener`. You can have a look at the example project.
