### ISSUE TITLE
Emojiconize.activity(this).go() error

### ISSUE THREAD

**Issue by 925941723** [rockerhieu/emojicon#154]
Cannot find package io.github.rockerhieu.emojiconize.Emojiconize ,I have been added 'io.github.rockerhieu:emojicon:1.4.1' .

**Comment by rockerhieu** [comment]
Emojiconize is a different library, you'll have to add it to your project as well: https://github.com/rockerhieu/emojiconize

**Comment by voghDev** [comment]
+1 having this issue. We both fell in the same mistake. Maybe the documentation should be clearer about this, telling that the line

    Emojiconize.activity(this).go() 

belongs to another library

**Comment by rockerhieu** [comment]
I will update the doc soon. Thanks!
