### ISSUE TITLE
how to change size of emojiconSize programmatically ?

### ISSUE THREAD

**Issue by miladr0** [rockerhieu/emojicon#165]

**Comment by emirmg** [comment]
X  KW  BNQHL NPD B-) VBBNHNGHH

**Comment by kot331107** [comment]
@miladr0 hope it will help:
`emojiconTextView.setEmojiconSize(32); //32 pixels. `
Use something like `(int)(32*getResources().getDisplayMetrics().density)` to set size 32dp from code

**Comment by miladr0** [comment]
@kot331107 tnx for your help
