### ISSUE TITLE
Could not find method bintray() for arguments [bintray_76nw0u7j417qv9737qxp1fqli$_run_closure6@a1d2b78] on project ':library' of type org.gradle.api.Project.

### ISSUE THREAD

**Issue by hErBiDoY** [rockerhieu/emojicon#176]
In the library's build.gradle... the apply from: bintray.gradle. causes this build error

**Comment by rockerhieu** [comment]
In https://github.com/rockerhieu/emojicon/blob/master/library/build.gradle I see that statement is commented. It should not cause any issue.
