### ISSUE TITLE
emojicon:emojiconSize doesn't work

### ISSUE THREAD

**Issue by Borys216307** [rockerhieu/emojicon#38]
Hello, Everyone!

I have kept trying to change the size of the emojicons shown on my chat app which uses this repository for 2 days but eventually failed.

I have tried several options: XML layout, runtime modification on the emojicon size.

1. Here's what I used in my layout.
...
<com.rockerhieu.emojicon.EmojiconTextView
                            android:id="@+id/me_tv"
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:text=""
			    emojicon:emojiconSize="500sp"
                            android:paddingRight="7dp"
                            android:textColor="@android:color/white" />

2. And here comes the runtime modification code
holder.s_mesg = (EmojiconTextView) convetView.findViewById(R.id.me_tv);
holder.s_mesg.setEmojiconSize(40);

Thanks, in advance.
Borys

**Comment by jagatappv** [comment]
Hey,
I am having same issue.
Why its not increasing emoji icon size.

This is my code:
 <com.rockerhieu.emojicon.EmojiconTextView
                    android:id="@+id/tvDescription"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginTop="10dp"
                    android:text="@string/app_name"
                    emojicon:emojiconSize="25sp"
                    android:textColor="@color/black" />

Its not increasing size, i tried with changing emojicon:emojiconSize to higher.

**Comment by rockerhieu** [comment]
Checking...

**Comment by rockerhieu** [comment]
I change `emojicon:emojiconSize` in `activity_main.xml` of the example project, it is working perfectly fine. Closing the issue.

**Comment by Sermilion** [comment]
Does not work for me.
