### ISSUE TITLE
Seems to be wrong release version. Example not working for using unsupported method

### ISSUE THREAD

**Issue by felixswang** [rockerhieu/emojicon#41]
Using IntelliJ and importing as 

compile 'com.rockerhieu.emojicon:library:1.0'

However, in EmojiActivity.java, none of 

mEditEmojicon.setUseSystemDefault(b)
mTxtEmojicon.setUseSystemDefault(b)
EmojiconsFragment.newInstance(useSystemDefault)

could be found. 

Did I config the dependencies wrong or the library has a version mismatch with the example?

Thanks,

- Felix

**Comment by Egorand** [comment]
Hi @rockerhieu 

Any plans to release 1.1 to the Maven Central?

Thanks
Egor

**Comment by rockerhieu** [comment]
@Egorand you could continue using `1.1-SNAPSHOT`. If there is nothing critical coming up, I will release it to maven in couple days.

**Comment by rockerhieu** [comment]
`1.1` is deployed! Please give it sometimes to sync to maven central.

**Comment by rockerhieu** [comment]
The deployment was be rejected. Checking...

**Comment by rockerhieu** [comment]
Confirmed, 1.1 is on maven central
