### ISSUE TITLE
How to getText + with Emojis from EmojiconEditText and send to webservice

### ISSUE THREAD

**Issue by qadir227** [rockerhieu/emojicon#43]
First let me thanks for sharing such an awesome library

I have implemented the EmojiconEditText in my app. Now I want to get the Text+Emojis from the Edit Text. and then I want to send the text to a php service and save in the My Sql Database. 

Im getting the (??????????) instead of the Emojis via myEditText.getText().toString(); is there any other method for this.

Please Help

**Comment by SqualalaTeam** [comment]
@dhams 

How can I implement this with Retrofit please ?
