### ISSUE TITLE
Cannot Resolve method Type Boolean

### ISSUE THREAD

**Issue by harishannam** [rockerhieu/emojicon#45]
@rockerhieu 
I used your example code in my project. Used the same Layout file. Imported the dependencies in gradle. Everything is done as mentioned. But still I get an error in the Cannot Resolve method error for

"setUseSystemDefault(b)" and "EmojiconsFragment.newInstance(useSystemDefault)"

Am I missing something?

**Comment by Neno0o** [comment]
I have the same problem. Have you any luck to solve it?

**Comment by harishannam** [comment]
Not yet, I gave up. If you get any solution, please update it here.

**Comment by daniele-athome** [comment]
Guys it's probably the maven cache gone crazy. Clear everything in ~/.m2 and invalidate cache and restart from Android Studio.

**Comment by harishannam** [comment]
No, Actually the EmojisFragment.class is not having the necessary code when it is imported through maven. Please help what to do regarding this.

**Comment by daniele-athome** [comment]
In that case it might be a maven deployment problem. @rockerhieu should intervene.

**Comment by elprudenciado** [comment]
Any updates about this issue? I also experiencing this right now. If no fix yet, any alternatives or workaround?

**Comment by rockerhieu** [comment]
Could you guys check again with `1.1-SNAPSHOT`? I'm deploying `1.1` to maven but getting network error, will try again tomorrow.

**Comment by rockerhieu** [comment]
`1.1` is deployed! Please give it sometimes to sync to maven central.

**Comment by rockerhieu** [comment]
Hmm, the deployment was be rejected. Checking...

**Comment by rockerhieu** [comment]
Confirmed, `1.1` is on maven central https://github.com/rockerhieu/emojicon/issues/41

**Comment by AmirHadifar** [comment]
@rockerhieu 
Same Issue , and I also add  compile 'com.rockerhieu.emojicon:library:1.1-SNAPSHOT' to build.gradle but gave me error can not resolve ! How can i fix this ?

**Comment by suraj9781** [comment]
I am  also facing same issue  with 1.0
