### ISSUE TITLE
Error inflating class fragment

### ISSUE THREAD

**Issue by yfeizi** [rockerhieu/emojicon#47]
when i add the emoji list fragment (EmojiconsFragment) like the example , its return this error : `ERROR/AndroidRuntime(419): FATAL EXCEPTION: main
        java.lang.RuntimeException: Unable to start activity ComponentInfo{info.guardianproject.otr.app.im/info.guardianproject.otr.app.im.app.ChatViewActivity}: android.view.InflateException: Binary XML file line #89: Error inflating class fragment`

**Comment by daniele-athome** [comment]
Please paste the full stacktrace, including the root cause.

**Comment by yfeizi** [comment]
i resolved this ! sorry but please add to readme that the host activity must implement `OnEmojiconClickedListener` and `OnEmojiconBackspaceClickedListener` :-)

**Comment by daniele-athome** [comment]
@yfeizi you should be able to close the issue, please do it (I'm not a project member).
