### ISSUE TITLE
Ellipsis for emojicon

### ISSUE THREAD

**Issue by seema7** [rockerhieu/emojicon#48]
when i enter more emojicons and they are out of the view then I am not able to show ellipsis. I tried android:singleLine="true"
 android:ellipsize="end" 
but not working.
Please help.

**Comment by daniele-athome** [comment]
It happens with Android stock apps too. Seems to be a limitation of some kind. I tried to look for a solution, didn't find any.

**Comment by rockerhieu** [comment]
I can see the ellipsize just fine:
```java
<com.rockerhieu.emojicon.EmojiconTextView
    app:emojiconSize="18dp"
    tools:text="Hey man, do you see 😁 😁 😁 😁 😁 😁 😁 😁 "
    android:lines="1"
    android:ellipsize="end"
    android:layout_width="match_parent"
    android:layout_height="wrap_content" />
```

Maybe you could find the answer here: http://stackoverflow.com/questions/6768977/text-does-not-ellipsize

**Comment by daniele-athome** [comment]
@rockerhieu did you try by placing more letters (so the letters overflow) and some emojis at the end? In some cases (such as a ListView item) you can a half emoji at the end. But that's probably a different case from the one OP described.

**Comment by seema7** [comment]
@rockerhieu I tried your solurion and it works only when text is there at the end not for emojicons.
Half emoji is displayed when Emoji is at the end or emojis that are  out of the view. Please help.

**Comment by AttITuder** [comment]
@daniele-athome How did you solve the problem at last?

**Comment by AttITuder** [comment]
@rockerhieu when i enter more emojicons and they are out of the view then I am not able to show ellipsis.Please help.

**Comment by daniele-athome** [comment]
@AttITuder I did not solved it.

**Comment by AttITuder** [comment]
@daniele-athome How did you deal with it?

**Comment by daniele-athome** [comment]
The bug is still there :-(

**Comment by tongcpp** [comment]
@AttITuder @daniele-athome This class almost saves me : https://github.com/google/iosched/blob/master/android/src/main/java/com/google/samples/apps/iosched/ui/widget/EllipsizedTextView.java

**Comment by jayronlou** [comment]
Tong Wong(tongcpp)'s   url can't open ,now please open this class :https://android.googlesource.com/platform/external/iosched/+/HEAD/android/src/main/java/com/google/samples/apps/iosched/ui/widget/EllipsizedTextView.java
