### ISSUE TITLE
Publish 1.1 and SNAPSHOTS releases to maven

### ISSUE THREAD

**Issue by Wirwing** [rockerhieu/emojicon#51]
Hi!

I'm trying to compile library with 1.1 version, but maven artifact is not being found. Is there any chance you could please push the latest version. Same with 1.2-SNAPSHOT.

Thanks in advance!

**Comment by rockerhieu** [comment]
Weird, I could find them:
* http://maven-repository.com/artifact/com.rockerhieu.emojicon/library/1.1
* https://oss.sonatype.org/content/repositories/snapshots/com/rockerhieu/emojicon/library/1.2-SNAPSHOT/

Please double check the dependencies configuration.
