### ISSUE TITLE
Library not working.

### ISSUE THREAD

**Issue by senthilzohocorp** [rockerhieu/emojicon#53]
Hi your library works fine when lazy swipe is not enabled. once i install and enable lazy swipe app emoji keyboard doesn't show.

**Comment by rockerhieu** [comment]
What is lazy swipe? Can you explain?

**Comment by senthilzohocorp** [comment]
Lazy swipe is a widget like app that allows us to configure and launch apps
from desktop.I attached the screenshot below on the issue.

**Comment by rockerhieu** [comment]
Is this Lazy Swipe you mentioned: https://play.google.com/store/apps/details?id=com.lazyswipe&hl=en
Could you please provide more details on the issue? i.e logs, screenshot (or video)?

**Comment by senthilzohocorp** [comment]
Ya...exactly the same app..I already attached screenshot...after installing
this, the smiley keyboard moved above keyboard
