### ISSUE TITLE
won't build for me

### ISSUE THREAD

**Issue by h-2** [rockerhieu/emojicon#54]
Hi,

I am trying to build Kontalk which pulls in emojicon as a submodule, but it fails:
http://pastebin.com/Q4VRhnyF

I have also tried directly building emojicon with `./gradlew clean build --debug` , it results in the following log:
http://pastebin.com/Zj5L1rZi

Thanks for your help!

**Comment by daniele-athome** [comment]
@h-2 building emojicon directly from our forks fails because of modifications I've made to the library and the example app is incompatible now.
Anyway what steps did you use to download all the stuff? Also git submodule commands etc.

**Comment by h-2** [comment]
I did `git clone --recursive https://github.com/kontalk/androidclient`
Then I spent half of the day making the android-sdk work.
Then I ran `./gradlew clean build` in the androidclient directory and produced the first pastebin. Trying to run gradle in the subdir was just wild guessing...

(I am also in the IRC, in case you want to reach me faster)

**Comment by daniele-athome** [comment]
I can build master successfully using

```
./gradlew build
```

Try to cleanup your environment:

* delete ~/.m2
* delete androidclient/.gradle
* delete androidclient/*/build

Also please check your SDK installation too (you need API level 21 and build tools 21.1.2).

**Comment by h-2** [comment]
I tried all of that, but it doesn't help, same results :sob: 
Maybe its related to my setup, I don't know. I am actually running an oracle jdk compiled for 32bit Linux through the linux binary compatibility layer of FreeBSD (64bit), it seems utterly ridiculous for a language that claims cross-platformness as number one feature, but oh well. I will investigate it further when I have time again. 
Thanks for your help anyhow!

**Comment by daniele-athome** [comment]
@h-2 I'm sorry but I can't help you with FreeBSD...

**Comment by h-2** [comment]
@daniele-athome 
Yeah, no problem, I wouldn't want you to spend more time on it anyway, as there are many more important things to do on Kontalk ;)
