### ISSUE TITLE
Getting error after adding the library to gradle

### ISSUE THREAD

**Issue by payamprivate** [rockerhieu/emojicon#62]
Hi everyone , I try to add the library to my project ,after adding the gradle ->
compile 'com.rockerhieu.emojicon:library:1.0'

I get this error in android studio:
Error:(13, 9) Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@icon value=(@mipmap/ic_launcherr) from AndroidManifest.xml:13:9
  	is also present at com.rockerhieu.emojicon:library:1.0:4:45 value=(@drawable/ic_launcher)
  	Suggestion: add 'tools:replace="android:icon"' to <application> element at AndroidManifest.xml:11:5 to override

with some search in google and stackoverflow I find out a solution
solution is that , if add this line of code to my manifest it can solve the error ->
tools:replace='android:icon'

I add the code , the error for icon gone , but now i have another error:
Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Users/payamprivate/Library/Android/sdk/build-tools/21.1.2/aapt'' finished with non-zero exit value 1

can someone help me , to solve the problem ... thanks

**Comment by Joqus** [comment]
I am having a similar problem, check this out:

http://stackoverflow.com/questions/29965398/gradle-finished-with-non-zero-exit-value-1-ic-launcher-png-error-duplicate-fi

**Comment by TakWolf** [comment]
There is an image resourse "ic_launcher.png"  conflict, you can add library manual.This is author's negligence.

Step:

1. clone the project.

2. Find library folder and delete  all "ic_launcher.png" in library.

3.copy library folder to your project root path and rename "library" to "emojicon-library"

4. In "settings.gradle" add "include 'emojicon-library'

5.In "app/build.gradle" include like this :  compile project(':emojicon-library')

Enjoy it :)

**Comment by Kentverger** [comment]
I use `compile 'com.rockerhieu.emojicon:library:1.2'` and this problem persist.

What extra information do you need to replicate the error?

**Comment by rockerhieu** [comment]
@Kentverger please use `1.3.1`.
