### ISSUE TITLE
New release sugestion

### ISSUE THREAD

**Issue by mazoni** [rockerhieu/emojicon#64]
Guys, I've just leaving this as a reminder to release a new version (1.0.1) or so, since this build.gradle line:
```groovy
compile 'com.android.support:support-v4:+'
```
is now the reason why this library must now be included like this:

```groovy
compile ('com.rockerhieu.emojicon:library:1.0') {
        exclude group: 'com.android.support', module:'support-v4'
    }
```
since the new support-v4:22.2.0 has some breaking issues related to missing classes and interfaces.
I did notice that the new build.gradle is now fixed, so it's just a matter of creating a new release.
The library is pretty cool by the way.

Regards.

**Comment by rockerhieu** [comment]
Done.
