### ISSUE TITLE
Library problems......

### ISSUE THREAD

**Issue by EpsilonOrionis** [rockerhieu/emojicon#67]
Why don't you update your project? The compile('...') for the 1.1 SNAPSHOT version in gradle returns an error and the 1.0 doesn't work. It isn't easy to implement in our projects and so on... I think that if you respect your work and yourself, you should upgrade this project as soon as possible, because it represents you. You've created a library that works only with your demo. You should make it  more flexible to be easily implemented in our projects. Thank you in advance. Sorry for this poem but I had to do it.

**Comment by rockerhieu** [comment]
There are newer versions on Maven. Check them out and let me know.
