### ISSUE TITLE
Cross platform Emoji Support

### ISSUE THREAD

**Issue by sagarlotus** [rockerhieu/emojicon#73]
This emoji library is part of one of my android application,same application have desktop client also. Sent emoji can view mobile to mobile. But for cross platform facing issue that while passing emoji through desktop to mobile n vice versa,respective emoji is not reflecting at another client, Rather it shows single box only.

Kindly advice for cross platform emoji support.

**Comment by daniele-athome** [comment]
I don't think this is easily possible. GUI toolkits and frameworks are very different between platforms. It would require a major refactoring to support multiple "pluggable" interface modules for the different UI frameworks (Android, Swing, SWT). I don't know how much effort @rockerhieu could put into this.

**Comment by sagarlotus** [comment]
@daniele-athome Thanks for rely. Can you suggest me some way to get out of this?

**Comment by daniele-athome** [comment]
You may reuse the emoji-specific parts such as emoji-unicode mappings, but that's all. The UI parts must be rewritten, sorry.

**Comment by sagarlotus** [comment]
@daniele-athome But what exactly means UI parts. I am not getting the technical term for the same.

**Comment by daniele-athome** [comment]
Controls, widgets, layouts, it's Android stuff. Clearly you can't use them on desktop.

**Comment by sagarlotus** [comment]
@daniele-athome  Okies. I think i have to make the changes on both sides i.e. android end and desktop end. And in my opinion i think uni code mapping is only correct way what u also saying.

**Comment by rockerhieu** [comment]
I have no plan to support `emojicon` outside of Android. But you can implement one by reusing the emoji mapping.
