### ISSUE TITLE
Console errors:  libpng warning: iCCP: Not recognizing known sRGB profile that has been edited

### ISSUE THREAD

**Issue by woodcockjosh** [rockerhieu/emojicon#75]
Theses warnings are generated when building

1.3.1/res/drawable-nodpi/emoji_1f4bd.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
1.3.1/res/drawable-nodpi/emoji_1f555.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited

It needs to be cleaned up with meta data removal
http://brewformulas.org/exiftool

You can fix the issue with this command 
`find . -path '*src/main/res/*' -name '*.png' -exec exiftool -overwrite_original -all= {} \;`

**Comment by rockerhieu** [comment]
Thanks, I will fix it in the next few hours

**Comment by rockerhieu** [comment]
Fixed in b7cf766.

**Comment by woodcockjosh** [comment]
Thanks!


Sent via the Samsung GALAXY S® 5, an AT&T 4G LTE smartphone


-------- Original message --------
