### ISSUE TITLE
Layout Problem in mobiles have on screen button.

### ISSUE THREAD

**Issue by soban-shareviasms** [rockerhieu/emojicon#76]
When run in nexus 5 which have on screen buttons instead of physical buttons like back, home, task.

emoji keyboard went above the keyboard and hides the edittext.
Kindly solve this problem.

**Comment by rockerhieu** [comment]
Can you send a screenshot?

**Comment by soban-shareviasms** [comment]
1st screenshot when keyboard is hide and 2nd screenshot when keyboard already opened..

**Comment by soban-shareviasms** [comment]
1st screenshot when keyboard is hide and 2nd screenshot when keyboard already opened..
![bug 01](https://cloud.githubusercontent.com/assets/13640323/9734406/3a9c51c6-564c-11e5-9c46-ae239bbbe9b4.png)

![bug 02](https://cloud.githubusercontent.com/assets/13640323/9734413/420378ea-564c-11e5-9a99-6cdc00cd2566.png)

**Comment by rockerhieu** [comment]
I don't think it has anything to do with the library. Can you send me your layout file and the code?

**Comment by soban-shareviasms** [comment]
Problem is emoji keyboard height. 
It include the onscreen buttons in keyboard height.

And no invoke the keyboard when keyboard is hidden.
So, it takes the height according to on screen button height.

**Comment by rockerhieu** [comment]
This issue is out of the library scope. Closing.
