### ISSUE TITLE
warning: iCCP: Not recognizing known sRGB?

### ISSUE THREAD

**Issue by gdky005** [rockerhieu/emojicon#78]
In Android Studio, gradle complie(gradle clean, gradle build)

:Android_KaolaFM:mergeDebugResources
AAPT: /Users/XXX/build/intermediates/exploded-aar/com.rockerhieu.emojicon/library/1.2/res/drawable-nodpi/emoji_1f4bd.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited

AAPT: /Users/XXX/build/intermediates/exploded-aar/com.rockerhieu.emojicon/library/1.2/res/drawable-nodpi/emoji_1f555.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
:Android_KaolaFM:processDebugManifest

This is a bug?

**Comment by rockerhieu** [comment]
Can you try `1.3.1` instead?

**Comment by rockerhieu** [comment]
Fixed in https://github.com/rockerhieu/emojicon/pull/70.
