### ISSUE TITLE
Emoji code and icons

### ISSUE THREAD

**Issue by MarianVasilca** [rockerhieu/emojicon#83]
Hello, where can i found a list with all emoticons supported and their afferent codes? ths

**Comment by daniele-athome** [comment]
All image files are here:
https://github.com/rockerhieu/emojicon/tree/master/library/src/main/res/drawable-nodpi

The mapping is inside the source code, but suffice it to say that the filename suffix of the images is the unicode hex value. You can see the actual mapping here:
https://github.com/rockerhieu/emojicon/blob/master/library/src/main/java/com/rockerhieu/emojicon/EmojiconHandler.java

**Comment by adolfdsilva** [comment]
If you could add this in readme it would be great..
Thanks!!!
