### ISSUE TITLE
Gradle build error. 

### ISSUE THREAD

**Issue by adolfdsilva** [rockerhieu/emojicon#89]
Hi,

Getting below error during build 
    Error:(8) No resource identifier found for attribute 'emojiconAlignment' in package 'package name'

Using build tools 23.0.2

**Comment by rockerhieu** [comment]
@adolfdsilva can you post your build script?

**Comment by tuhin10** [comment]
Warning:Project app: apk dependencies can only be jars. com.rockerhieu.emojicon:library:aar:1.3.1 is an Android Library.

**Comment by rockerhieu** [comment]
@tuhin10 can you post your build script?
