### ISSUE TITLE
Apk size increases by 3mb

### ISSUE THREAD

**Issue by VihaanVerma89** [rockerhieu/emojicon#90]
Hey, 

I added your library and the size of my apk increased by 3 mbs. Are you also shipping lots of images with the library ?

Thanks
Vihaan

**Comment by daniele-athome** [comment]
What do you think?
:-)

**Comment by VihaanVerma89** [comment]
I'm guessing it's the images. Can't be sure unless I check the source code :|

**Comment by daniele-athome** [comment]
You're right, it's the actual emojis taking all that space.

**Comment by naveedrocks1** [comment]
@VihaanVerma89 were you able to add this lib?
